# Num Py Array

In [5]:
#printing array with the help of List
import numpy as np
a=np.array([0,1,2,3,4,5]) #func of list
print(a)

#printing array of 0-9
print(np.arange(10))

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


# NumPY Faster

In [8]:
lst=range(1000)
%timeit [i**2 for i in lst] 

440 µs ± 7.89 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
a=np.arange(1000)
%timeit a**2

2.17 µs ± 16.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# 1.Creating Arrays

# 1.1. Manual Construction of Array

# 1-D Array

In [17]:
# 1-D Arrays
a=np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [16]:
#print dimensions
a.ndim

1

In [13]:
#shape #6 elements
a.shape

(6,)

In [60]:
a.size

6

# List Of List

In [49]:
#List of list Array
b=np.array([[0,1,2,3,4],[6,7,8,9,10]],dtype=object)
b

array([[0, 1, 2, 3, 4],
       [6, 7, 8, 9, 10]], dtype=object)

In [50]:
#print dimensions
b.ndim

2

In [51]:
#shape 
b.shape

(2, 5)

In [52]:
#returns the size of the first dimension
len(b)

2

In [59]:
b.size

10

# 2D  Array

In [44]:
c=np.array([[0,1,2,3,4,],[5,6,7,8,9]],dtype=np.int32)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
#print dimensions
c.ndim

2

In [47]:
#shape 
c.shape

(2, 5)

In [48]:
#returns the size of the first dimension
len(c)

2

In [58]:
c.size

10

# 3D Arrays

In [63]:
#list within list within list
#CUBOID like
d=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [55]:
d.ndim

3

In [56]:
d.size

8

In [64]:
d.shape
#tuple(len=2,brd=2,dep=2)

(2, 2, 2)

# 1.2. Functions for creating Arrays

# Using Arrange Function

In [66]:
a=np.arange(10) #0....9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a=np.arange(1,10,2) #0...9 with 2 step size
a

array([1, 3, 5, 7, 9])

In [78]:
a=np.arange(0,1,0.2,dtype=np.float64) #0...9 with 2 step size
a


array([0. , 0.2, 0.4, 0.6, 0.8])

# Using Linspace

In [79]:
#start,end,no of points
a=np.linspace(0,1,6) 
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [81]:
#start,end,no of points
a=np.linspace(1,3,6) 
a

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

# Common Array

In [87]:
a=np.ones((3,3)) #func of tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
b=np.zeros((3,3)) #float
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [88]:
#Identity 2-D array
c=np.eye(3)
c


array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [89]:
# 3rows and 2 columns
d=np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

# Diagonal Functions

In [90]:
#creating array using diagonal func
a=np.diag([1,2,3,4]) #4X4 Matrix
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [91]:
#extract Diagnonal elements
np.diag(a) 

array([1, 2, 3, 4])

# Random Array

In [92]:
#uniform random no
a=np.random.rand(4)
a

array([0.65711732, 0.26852209, 0.98336764, 0.33739764])

In [95]:
#Gausian Rndom no/standard normal no
a=np.random.randn(4)
a

array([-1.23171037,  1.42584114,  0.0513131 , -0.7750699 ])

# 2.Basic DataTypes

In [101]:
a=np.arange(10)
print(a)
a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [98]:
#Explicity specify which data-type want:
a=np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [102]:
#The default data type is float for zeros and ones function
a=np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [103]:
d=np.array([1+2j,2+3j]) #complex no
d.dtype

dtype('complex128')

In [104]:
e=np.array([True,False,False,True])
print(e.dtype)

bool


In [106]:
s=np.array(['Hi','Hello'])
s.dtype

dtype('<U5')

# 3. Indexing

In [109]:
#1-D Array
a=np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [114]:
#Multi Dimension  Array
a=np.diag([1,2,3])
print(a)
print(a[0,0])
print(a[1,1])
print(a[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
1
2
3


In [117]:
#assigning the value in the matrix
a[2,1]=5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

# 4.Slicing

In [118]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
a[1:8:2] #start,stop,stepsize

array([1, 3, 5, 7])

In [121]:
a=np.arange(10)
print(a)
a[5:]=10
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [124]:
b=np.arange(5)
print(b)
a[5:]=b[::-1] #assigning on 5th onwards 
#start=0, end =len(a), stepsize=-1
a

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 5.Copies and Views

In [125]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [127]:
np.shares_memory(a,b)

True

In [129]:
b[0]=10
b

array([10,  2,  4,  6,  8])

In [131]:
a #a is also modified becoz same memory location

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [136]:
#Forcing copying so that memory location different
a=np.arange(10)
c=a[::2].copy() #force copy
c

array([0, 2, 4, 6, 8])

In [134]:
np.shares_memory(a,c)

False

In [137]:
c[0]=10
a #no changes in a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 6.Fancy Indexing

In [145]:
a=np.random.randint(0,20,15) #start=0,end=20,15 such nos
a

array([15,  9, 14, 16,  2,  4, 17,  9,  4,  7, 14,  0, 17, 18, 14])

a=np.random.randint(0,20) #start=0,end=20,1 nos
a

In [146]:
#choosing only even no
mask=(a%2==0)

In [147]:
extract_from_a=a[mask]
extract_from_a

array([14, 16,  2,  4,  4, 14,  0, 18, 14])

Indexing with mask can be very useful to assign a new value to sub-array

In [148]:
a[mask]=-1 # all even becomes -1
a

array([15,  9, -1, -1, -1, -1, 17,  9, -1,  7, -1, -1, 17, -1, -1])

Indexing with an array of integers

In [149]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [152]:
#indexing with array of integers
a[[0,2,4,6,7,8,9]]

array([ 0, 20, 40, 60, 70, 80, 90])

In [153]:
#assigning value
a[[8,9]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60,   70, -200, -200])

In [154]:
#assigning value
a[[8,7]]=-200
a

array([   0,   10,   20,   30,   40,   50,   60, -200, -200, -200])